d = {
    data: {
        id: 46,
        ownerId: 16,
        hypervisorId: 1,
        arch: 1,
        name: 'Partial Mark',
        selfService: 0,
        selfServiceSettings: [],
        hostname: null,
        commissionStatus: 3,
        uuid: '60f619ac-b17f-4168-9554-0ac7b8811f3d',
        state: 'complete',
        migratable: true,
        timezone: '_default',
        migrateLevel: 0,
        deleteLevel: 0,
        configLevel: 0,
        backupLevel: 0,
        elevated: false,
        elevateId: null,
        elevate: false,
        destroyable: true,
        rebuild: false,
        suspended: false,
        protected: false,
        buildFailed: false,
        primaryNetworkDhcp4: false,
        primaryNetworkDhcp6: false,
        built: '2025-02-07T20:02:09+00:00',
        created: '2025-02-07T20:01:21+00:00',
        updated: '2025-02-07T20:02:09+00:00',
        traffic: { public: [Object] },
        settings: {
            osTemplateInstall: true,
            osTemplateInstallId: 19,
            encryptedPassword: 'eyJpdiI6IitlUHJQNExsc0Z6b09LQ1lraFZVMXc9PSIsInZhbHVlIjoiNGlMand6eHd5TEFiMDhER0FBNTVoLzU1bDBTL3BHTWg4QldZUVF6Z2dicz0iLCJtYWMiOiIyMDkzMjE1Y2E3YjQxMmQzNDQzYTM0MzY0ZmMxNTA4MjYwMDZlZWUxZTJjYTNjODFkMjUyYmNmNGRmODg3YjA1IiwidGFnIjoiIn0=',
            backupPlan: null,
            uefi: false,
            uefiType: 0,
            cloudInit: true,
            cloudInitType: 2,
            config: [Object],
            userConfig: [],
            bootOrder: [Array],
            tpmType: 0,
            networkBoot: false,
            bootMenu: 1,
            customISO: 1,
            securityDriver: 3,
            memBalloon: [Object],
            hyperv: [Object],
            extended: [Object],
            machineType: 'inherit',
            pciPorts: 16,
            resources: [Object]
        },
        cpu: {
            cores: 4,
            type: 'host-model',
            typeExact: 'host-model',
            shares: 1024,
            throttle: 0,
            topology: [Object]
        },
        customXML: {
            domain: [Object],
            os: [Object],
            devices: [Object],
            features: [Object],
            clock: [Object],
            cpuTune: [Object]
        },
        qemuCommandline: [],
        qemuAgent: { os: [Object] },
        media: {
            isoMounted: false,
            isoType: 'local',
            isoName: '',
            isoFilename: '',
            isoUrl: '',
            isoDownload: false
        },
        backupPlan: { id: null, name: null },
        vnc: { ip: '193.111.250.208', port: 5914, enabled: false },
        network: { interfaces: [Array], secondaryInterfaces: [] },
        storage: [
            [Object]
        ],
        hypervisorAssets: [],
        hypervisor: {
            id: 1,
            ip: '193.111.250.208',
            hostname: null,
            port: 8892,
            maintenance: false,
            groupId: 1,
            group: [Object],
            timezone: 'Europe/London',
            forceIPv6: false,
            vncListenType: 1,
            displayName: null,
            nfType: 0,
            backupStorageType: 1,
            defaultDiskType: 'qcow2',
            defaultDiskCacheType: 'inherit',
            defaultCPU: 'host-model',
            defaultMachineType: 'inherit',
            created: '2025-02-04T21:31:22+00:00',
            updated: '2025-02-05T18:47:16+00:00',
            name: 'node-S140',
            dataDir: '/home/vf-data',
            resources: [Object]
        },
        owner: {
            id: 16,
            admin: false,
            extRelationId: null,
            name: 'DR.AL56ER',
            email: 'abodi3238FAa@gmail.com',
            timezone: 'Europe/London',
            suspended: false,
            twoFactorAuth: false,
            created: '2025-02-07T20:01:05+00:00',
            updated: '2025-02-07T20:01:05+00:00'
        },
        sshKeys: [],
        sharedUsers: [],
        tasks: { active: false, lastOn: '2025-02-07 20:03:29', actions: [Object] },
        remoteState: false
    }
}